# Generated by Django 4.2.7 on 2024-05-10 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('towing', 'Towing'), ('flat_battery', 'Flat Battery'), ('fuel_delivery', 'Fuel Delivery'), ('lost_key', 'Lost Key'), ('flat_tire', 'Flat Tire'), ('diagnostic', 'Diagnostic')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bankily', 'bankily'), ('masrvi', 'Masrvi')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='service_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('litres', models.FloatField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=10, null=True)),
                ('car_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('technician_type', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
