# Generated by Django 5.0.6 on 2024-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='technician_type',
            field=models.CharField(blank=True, choices=[('mechanic', 'Mechanic'), ('electrician', 'Electrician')], max_length=20, null=True),
        ),
    ]
