# Generated by Django 5.0.4 on 2024-05-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_carpart_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="carpart",
            name="category",
            field=models.CharField(
                choices=[
                    ("Engine", "Engine"),
                    ("Tire", "Tire"),
                    ("Brake", "Brake"),
                    ("Battery", "Battery"),
                    ("Lighting", "Lighting"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
