# Generated by Django 4.2.7 on 2024-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='job',
            field=models.CharField(choices=[('Mechanic', 'Mechanic'), ('Electrician', 'Electrician'), ('ShopOwner', 'Shop Owner'), ('Other', 'Other')], max_length=15),
        ),
    ]
