# Generated by Django 5.0.4 on 2024-05-28 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gps", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserLocation",
        ),
    ]
